#!/bin/bash
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
SRC="$HERE/vulkan_device_gate.c"
OUT="${VULKAN_DEVICE_GATE_OUT:-$HERE/vulkan-device-gate-x64.exe}"
RUNTIME_BUILD_ID="${DETROIT_RUNTIME_BUILD_ID:-standalone-unbound}"

find_cc() {
    if [ -n "${X86_64_W64_MINGW32_CLANG:-}" ] && [ -x "${X86_64_W64_MINGW32_CLANG}" ]; then
        printf '%s\n' "$X86_64_W64_MINGW32_CLANG"
        return 0
    fi
    if command -v x86_64-w64-mingw32-clang >/dev/null 2>&1; then
        command -v x86_64-w64-mingw32-clang
        return 0
    fi
    if command -v x86_64-w64-mingw32-gcc >/dev/null 2>&1; then
        command -v x86_64-w64-mingw32-gcc
        return 0
    fi
    local candidate
    candidate="$(find "$REPO_ROOT/toolchains" -type f \( -name 'x86_64-w64-mingw32-clang' -o -name 'x86_64-w64-mingw32-gcc' \) -perm -111 -print 2>/dev/null | head -n 1 || true)"
    if [ -n "$candidate" ]; then
        printf '%s\n' "$candidate"
        return 0
    fi
    return 1
}

CC="$(find_cc || true)"
if [ -z "$CC" ]; then
    echo "error: no x86_64 MinGW compiler was found" >&2
    echo "set X86_64_W64_MINGW32_CLANG=/path/to/x86_64-w64-mingw32-clang-or-gcc" >&2
    exit 2
fi

if [ "$RUNTIME_BUILD_ID" != "standalone-unbound" ] && [[ ! "$RUNTIME_BUILD_ID" =~ ^[0-9a-f]{64}$ ]]; then
    echo "error: DETROIT_RUNTIME_BUILD_ID must be exactly 64 lowercase hexadecimal characters" >&2
    exit 3
fi

IDENTITY_C="$(mktemp "${TMPDIR:-/tmp}/madeira-detroit-runtime-id.XXXXXX.c")"
trap 'rm -f "$IDENTITY_C"' EXIT
cat > "$IDENTITY_C" <<EOF
/* Generated by build-vulkan-device-gate.sh. The normal Detroit orchestrator
 * supplies a SHA-256 identity derived from the exact local Vulkan/Wine/FEX
 * runtime inputs. Because this string is embedded in the gate executable, the
 * existing physical-proof payload fingerprint changes whenever that runtime
 * changes, invalidating stale PASS proof automatically. */
const char madeira_detroit_runtime_build_id[] =
    "MADEIRA_DETROIT_RUNTIME_BUILD_ID=$RUNTIME_BUILD_ID";
EOF

echo "=== Madeira Detroit Vulkan device gate ==="
echo "compiler: $CC"
echo "output:   $OUT"
echo "runtime:  $RUNTIME_BUILD_ID"

"$CC" \
    -std=c11 -O2 -g \
    -Wall -Wextra -Werror \
    -o "$OUT" "$SRC" "$IDENTITY_C" \
    -lkernel32

# Fail closed if the compiler/linker somehow discarded the identity object.
if ! grep -aqF "MADEIRA_DETROIT_RUNTIME_BUILD_ID=$RUNTIME_BUILD_ID" "$OUT"; then
    echo "error: device gate does not contain the requested Detroit runtime identity" >&2
    exit 4
fi

if [ -n "${TEST_BUNDLE_DIR:-}" ]; then
    mkdir -p "$TEST_BUNDLE_DIR"
    cp -f "$OUT" "$TEST_BUNDLE_DIR/vulkan-device-gate-x64.exe"
    echo "copied:   $TEST_BUNDLE_DIR/vulkan-device-gate-x64.exe"
fi

if command -v file >/dev/null 2>&1; then
    file "$OUT"
fi

echo "PASS: Detroit Vulkan device gate built"
if [ "$RUNTIME_BUILD_ID" = "standalone-unbound" ]; then
    echo "NOTE: standalone build is not bound to a Detroit runtime; use build/detroit-vulkan/build.sh for physical qualification."
else
    echo "PASS: physical proof payload is bound to Detroit runtime $RUNTIME_BUILD_ID"
fi
echo "Success ends with OVERALL=PASS and NEXT_GATE=detroit-process-and-shader-compilation."
